FROM golang:1.26-alpine AS builder

WORKDIR /app/server

COPY server .

RUN go build -o serverBin .

# estagio 2

FROM alpine:3.20 AS final

WORKDIR /app

COPY --from=builder /app/server . 

CMD ["./serverBin"] 
